---
- name: Homebrew がインストールされているかチェック
  shell: which brew > /dev/null 2>&1
  register: homebrew_status
  changed_when: False
  tags: initial-packages

- name: Homebrew インストール（playbook 内で使うため初回に入れる）
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: homebrew_status.rc == 1
  tags: initial-packages

- name: Homebrew アップデート
  homebrew:
    update_homebrew: True
  tags: initial-packages

- name: Git インストール（playbook 内で使うため初回に入れる）
  homebrew:
    name: git
    state: present
  tags: initial-packages

- name: zsh インストール（playbook 内で使うため初回に入れる）
  homebrew:
    name: zsh
    state: present
  tags: initial-packages
