---
- name: brew tap
  homebrew_tap:
    name: "{{ item.tap }}"
    state: present
  when: item.tap is defined
  with_items: "{{ homebrew }}"

- name: install Homebrew packages
  homebrew:
    name: "{{ item.name }}"
    state: present
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ homebrew }}"
