---
- name: tap が必要なパッケージを brew tap する
  homebrew_tap:
    name: "{{ item.tap }}"
    state: present
  when: item.tap is defined
  with_items: "{{ homebrew }}"
  tags: homebrew

- name: Homebrew パッケージインストール
  homebrew:
    name: "{{ item.name }}"
    state: present
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ homebrew }}"
  tags: homebrew
