# ---------------------------------------------------------------------------- #
# ref: https://github.com/sasstools/sass-lint/tree/master/docs/rules
# 0: nothing, 1: warning, 2: error
# ---------------------------------------------------------------------------- #
#
options:
  formatter: stylish
  merge-default-rules: true
files:
  include: '*.scss'
rules:
  attribute-quotes: 2
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - style: '1tbs'
  class-name-format:
    - 1
    - allow-leading-underscore: true
      convention: 'hyphenatedbem'
  clean-import-paths:
    - 2
    - leading-underscore: false
      filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    - include: false
  empty-line-between-blocks: 0
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 1
    - allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-file-line-count:
    - 2
    - length: 1000
  max-line-length:
    - 1
    - length: 120
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  mixins-before-declarations: 0
  nesting-depth:
    - 2
    - max-depth: 4
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties:
    - 2
    - properties: []
  no-duplicate-properties:
    - 2
    - exclude: [ display ]
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 1
  no-url-protocols: 0
  no-vendor-prefixes: 1
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  property-sort-order: 0
  property-units: 0
  pseudo-element: 0
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands: [1, 2]
  single-line-per-selector: 2
  space-after-bang: 0
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang: 0
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: 'hyphenatedlowercase'
  zero-unit:
    - 2
    - include: false
