---
- name: Homebrew Cask の導入
  homebrew_tap:
    name: caskroom/cask
    state: present
  tags: homebrew-cask

- name: Homebrew Cask パッケージインストール
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ homebrew_cask }}"
  tags: homebrew-cask
