---

- name: install dependency packages for anyenv
  homebrew:
    name: libmcrypt
    state: present

- name: install anyenv (1/2)
  stat:
    path: ${ANYENV_ROOT}
  register: anyenv_status

- name: install anyenv (2/2)
  git:
    repo: https://github.com/riywo/anyenv
    dest: ${ANYENV_ROOT}
  when: not anyenv_status.stat.exists

- name: initial settings anyenv
  shell: eval "$(${ANYENV_ROOT}/bin/anyenv init -)"
  changed_when: False

- name: reboot shell
  shell: exec $SHELL -l
  changed_when: False
