---

- name: tilesize
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: "{{ dock.size }}"
    state: present

- name: magnification
  osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: "{{ dock.zoom }}"
    state: present

- name: autohide
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "{{ dock.autohide }}"
    state: present
