---
- name: set ComputerName (1/2)
  shell: scutil --get ComputerName
  register: computername_status
  changed_when: False
  tags: initial

- name: set ComputerName (2/2)
  shell: scutil --set ComputerName "{{ computer_name }}"
  when: computername_status.stdout != "{{ computer_name }}"
  become: True
  tags: initial

- name: set HostName (1/2)
  shell: scutil --get HostName
  register: hostname_status
  ignore_errors: True
  changed_when: False
  tags: initial

- name: set HostName (2/2)
  shell: scutil --set HostName "{{ computer_name }}"
  when: hostname_status.stdout != "{{ computer_name }}"
  become: True
  tags: initial

- name: set LocalHostName (1/2)
  shell: scutil --get LocalHostName
  register: localhostname_status
  ignore_errors: True
  changed_when: False
  tags: initial

- name: set LocalHostName (2/2)
  shell: scutil --set LocalHostName "{{ computer_name }}"
  when: localhostname_status.stdout != "{{ computer_name }}"
  become: True
  tags: initial

- name: install Homebrew (1/2)
  shell: which brew > /dev/null 2>&1
  register: homebrew_status
  changed_when: False
  tags: initial

- name: install Homebrew (2/2)
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: homebrew_status.rc == 1
  tags: initial

- name: update Homebrew
  homebrew:
    update_homebrew: True
  tags: initial

- name: install Git
  homebrew:
    name: git
    state: present
  tags: initial

- name: install zsh
  homebrew:
    name: zsh
    state: present
  tags: initial

- name: set symbolic links
  file:
    src: "~/dotfiles/{{ item.src  }}"
    dest: "~/{{ item.dest|default(item.src) }}"
    state: link
  with_items: "{{ symlinks }}"
  tags: initial
