---

- name: install rbenv (1/2)
  stat:
    path: /usr/local/anyenv/envs/rbenv/
  register: rbenv_status

- name: install rbenv (2/2)
  shell: anyenv install rbenv
  when: not rbenv_status.stat.exists

- name: initial settings rbenv
  shell: eval "$(anyenv init - $SHELL)"
  when: not rbenv_status.stat.exists

- name: install rbenv versions (1/2)
  shell: ls "${RBENV_ROOT}/versions"
  register: rbenv_versions_status
  changed_when: False

- name: install rbenv versions (2/2)
  shell: rbenv install "{{ item }}"
  when: rbenv_versions_status.stdout.find("{{ item }}") == "-1"
  with_items: "{{ rbenv.versions }}"

- name: set global ruby (1/2)
  shell: rbenv global
  register: rbenv_global_status
  changed_when: False

- name: set global ruby (2/2)
  shell: rbenv global "{{ rbenv.global }}"
  when: rbenv | length > 0 and (rbenv_global_status.stdout.find("{{ rbenv.global }}") == "-1")
