---
- name: コンピュータ名の取得
  shell: scutil --get ComputerName
  register: computername_status
  changed_when: False
  tags: initial-configuration

- name: コンピュータ名の指定
  shell: scutil --set ComputerName "{{ computer_name }}"
  when: computername_status.stdout != "{{ computer_name }}"
  become: True
  tags: initial-configuration

- name: ホスト名の取得
  shell: scutil --get HostName
  register: hostname_status
  changed_when: False
  tags: initial-configuration

- name: ホスト名の指定
  shell: scutil --set HostName "{{ computer_name }}"
  when: hostname_status.stdout != "{{ computer_name }}"
  become: True
  tags: initial-configuration

- name: ローカルホスト名の取得
  shell: scutil --get LocalHostName
  register: localhostname_status
  changed_when: False
  tags: initial-configuration

- name: ローカルホスト名の指定
  shell: scutil --set LocalHostName "{{ computer_name }}"
  when: localhostname_status.stdout != "{{ computer_name }}"
  become: True
  tags: initial-configuration

- name: 現在のユーザーアプリケーションの権限設定の取得
  shell: grep 'integer' /private/var/db/com.apple.xpc.launchd/config/user.plist | awk -F'<\/?integer>' '{print $2}' 2> /dev/null
  register: umask_user_status
  ignore_errors: True
  changed_when: False
  when: permission is defined
  tags: initial-configuration

- name: ユーザーアプリケーションの権限設定
  shell: launchctl config user umask "{{ permission }}"
  register: umask_user_result
  when: permission is defined and umask_user_status.stdout != "{{ permission | int }}"
  become: True
  tags: initial-configuration

- name: 現在のシステムアプリケーションの権限設定の取得
  shell: grep 'integer' /private/var/db/com.apple.xpc.launchd/config/system.plist | awk -F'<\/?integer>' '{print $2}' 2> /dev/null
  register: umask_system_status
  ignore_errors: True
  changed_when: False
  when: permission is defined
  become: True
  tags: initial-configuration

- name: システムアプリケーションの権限設定
  shell: launchctl config system umask "{{ permission }}"
  register: umask_system_result
  when: permission is defined and umask_system_status.stdout != "{{ permission | int }}"
  become: True
  tags: initial-configuration

- name: マルチユーザー用の設定チェック
  stat:
    path: /usr/local/
  register: multiuser_status
  changed_when: False
  tags: initial-configuration

- name: マルチユーザー用権限の設定
  file:
    path: /usr/local/
    group: staff
    state: touch
    mode: "0775"
  when: multiuser_status.stat.gr_name != "staff" or multiuser_status.stat.mode != "0775"
  become: True
  tags: initial-configuration

- name: ホストマシンの再起動が必要です
  fail:
    msg: "ホストマシンの再起動が必要です、必要なアプリケーションを閉じて再起動してください"
  when: umask_user_result.changed or umask_system_result.changed
  tags: initial-configuration
