---

- name: ask for password
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: "{{ 1 if security_and_privacy.ask_for_password else 0 }}"
    state: present

- name: ask for password delay
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: "{{ security_and_privacy.ask_for_password_delay }}"
    state: present

# TODO: 他では become: True が有効なのに、ここだとユーザー名が空になって無効となる、なぜ・・・
#- name: FileVault settings (1/2)
#  shell: fdesetup isactive
#  register: filevault_status
#  ignore_errors: True
#  changed_when: False
#
#- name: FileVault settings (2/2)
#  shell: fdesetup {{ "enable" if security_and_privacy.filevault else "disable" }}
#  when: (security_and_privacy.filevault is defined) and
#        (filevault_status.stdout == "true" and security_and_privacy.filevault != True) or
#        (filevault_status.stdout == "false" and security_and_privacy.filevault == True)
