# ---------------------------------------------------------------------------- #
# $HOME/.vim/settings/bundles-filetypes.toml
# ---------------------------------------------------------------------------- #

# ---------------------------------------------------------------------------- #
# filetype css, scss
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'stubbornella/csslint'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
filetypes = 'scss'



# ---------------------------------------------------------------------------- #
# filetype go
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = 'go'



# ---------------------------------------------------------------------------- #
# filetype html
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'
hook_add = '''
  let g:user_emmet_leader_key = '<C-y>'
'''

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'



# ---------------------------------------------------------------------------- #
# filetype javascript
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = 'javascript'
hook_add = '''
  let g:SimpleJsIndenter_BriefMode = 1

  let g:SimpleJsIndenter_CaseIndentLevel = 0
'''

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = 'javascript'



# ---------------------------------------------------------------------------- #
# filetype json
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'



# ---------------------------------------------------------------------------- #
# filetype markdown
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'
on_event = 'BufRead'



# ---------------------------------------------------------------------------- #
# filetype php
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
on_ft = 'php'

# [[plugins]]
# repo = 'violetyk/neocomplete-php.vim'
# on_ft = 'php'

[[plugins]]
repo = 'beanworks/vim-phpfmt'
on_ft = 'php'
hook_add = '''
  let g:phpfmt_standard = 'PSR2'
  let g:phpfmt_autosave = 1
'''

[[plugins]]
repo = 'flyinshadow/php_localvarcheck.vim'
on_ft = 'php'
hook_add = '''
  let g:php_localvarcheck_global = 1
'''



# ---------------------------------------------------------------------------- #
# filetype tmux
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'



# ---------------------------------------------------------------------------- #
# filetype toml
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'



# ---------------------------------------------------------------------------- #
# filetype typescript
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'



# ---------------------------------------------------------------------------- #
# filetype vim
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'ynkdir/vim-vimlparser'
on_ft = 'vim'

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = ['ynkdir/vim-vimlparser']
on_ft = 'vim'



# ---------------------------------------------------------------------------- #
# filetype yaml
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'darfink/vim-plist'
on_ft = 'xml'



# ---------------------------------------------------------------------------- #
# filetype yaml
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'avakhov/vim-yaml'
on_ft = 'yaml'
