# ---------------------------------------------------------------------------- #
# neobundle install repositories
# ---------------------------------------------------------------------------- #

# details :help neobundle#load_toml
#
# # TOML sample
# [[plugins]]
# # repository name is required.
# repo = 'kana/vim-niceblock'
# mappings = '<Plug>'
#
# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# depends = ['Shougo/neosnippet-snippets',
#   'Shougo/context_filetype.vim']
# insert = 1
# filetypes = 'snippet'
# unite_sources = [ 'neosnippet',
#   'neosnippet/user', 'neosnippet/runtime']
#
#   [[plugins.depends]]
#   repository = 'honza/vim-snippet'
#   name = 'honza-snippet'



# ---------------------------------------------------------------------------- #
# interface
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'Shougo/unite.vim'



# ---------------------------------------------------------------------------- #
# syntax
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'scrooloose/syntastic'



# ---------------------------------------------------------------------------- #
# completion
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'Shougo/neocomplete'

[[plugins]]
repository = 'Shougo/neosnippet'

[[plugins]]
repository = 'honza/vim-snippets'



# ---------------------------------------------------------------------------- #
# diff
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'vim-scripts/diffchar.vim'



# ---------------------------------------------------------------------------- #
# git, gist
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'cohama/agit.vim'

[[plugins]]
repository = 'lambdalisue/vim-gista'
depends    = ['Shougo/unite.vim', 'tyru/open-browser.vim']



# ---------------------------------------------------------------------------- #
# filer
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'Shougo/vimfiler'



# ---------------------------------------------------------------------------- #
# expand
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'tpope/vim-surround'

[[plugins]]
repository = 'vim-scripts/matchit.zip'

[[plugins]]
repository = 'osyo-manga/vim-jplus'

[[plugins]]
repository = 'mattn/emmet-vim'



# ---------------------------------------------------------------------------- #
# utility
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'kana/vim-fakeclip'

[[plugins]]
repository = 'Shougo/vimproc'

[[plugins]]
repository = 'thinca/vim-quickrun'

[[plugins]]
repository = 'junegunn/vim-easy-align'



# ---------------------------------------------------------------------------- #
# filetype css
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'stubbornella/csslint'
filetypes  = 'css'

[[plugins]]
repository = 'hail2u/vim-css3-syntax'
filetypes  = 'css'



# ---------------------------------------------------------------------------- #
# filetype go
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'fatih/vim-go'
filetypes  = 'go'

[[plugins]]
repository = 'vim-jp/vim-go-extra'
filetypes  = 'go'



# ---------------------------------------------------------------------------- #
# filetype html
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'othree/html5.vim'
filetypes  = 'html'

[[plugins]]
repository = 'hokaccha/vim-html5validator'
filetypes  = 'html'



# ---------------------------------------------------------------------------- #
# filetype javascript
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'pangloss/vim-javascript'
filetypes  = 'javascript'



# ---------------------------------------------------------------------------- #
# filetype json
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'elzr/vim-json'
filetypes  = 'json'



# ---------------------------------------------------------------------------- #
# filetype markdown
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'tpope/vim-markdown'
filetypes  = 'markdown'



# ---------------------------------------------------------------------------- #
# filetype php
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = '2072/PHP-Indenting-for-VIm'
filetypes  = 'php'

[[plugins]]
repository = 'violetyk/neocomplete-php.vim'
filetypes  = 'php'



# ---------------------------------------------------------------------------- #
# filetype scss
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'cakebaker/scss-syntax.vim'
filetypes  = 'scss'



# ---------------------------------------------------------------------------- #
# filetype toml
# ---------------------------------------------------------------------------- #

[[plugins]]
repository = 'cespare/vim-toml'
filetypes  = 'toml'

