# ---------------------------------------------------------------------------- #
# diff plugins
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'rickhowe/diffchar.vim'
hook_add = '''
  let g:DiffUnit = "Word3"
  let g:DiffUpdate = 1
'''
