# ---------------------------------------------------------------------------- #
# enhancement plugins
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
  let g:context_filetype#search_offset = 500
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']
hook_add = '''
  let g:context_filetype#filetypes = {
        \ 'typescript' : [
        \   {
        \     'start' : 'template:\s*`',
        \     'end' : '\s*`',
        \     'filetype' : 'html',
        \   },
        \   {
        \     'start' : 'styles:\s*[\s*`',
        \     'end' : '\s*`\s*]',
        \     'filetype' : 'css',
        \   }
        \ ],
        \}
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
  let g:surround_{char2nr("\<CR>")} = "\n\t\r\n"
'''

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'osyo-manga/vim-jplus'
hook_add = '''
  nmap <Space>J <Plug>(jplus-input)
  vmap <Space>J <Plug>(jplus-input)
'''

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  " window resize
  call submode#enter_with('winsize', 'n', '', '<C-w>>', '<C-w>>')
  call submode#enter_with('winsize', 'n', '', '<C-w><', '<C-w><')
  call submode#enter_with('winsize', 'n', '', '<C-w>+', '<C-w>+')
  call submode#enter_with('winsize', 'n', '', '<C-w>-', '<C-w>-')
  call submode#map('winsize', 'n', '', '>', '<C-w>>')
  call submode#map('winsize', 'n', '', '<', '<C-w><')
  call submode#map('winsize', 'n', '', '+', '<C-w>+')
  call submode#map('winsize', 'n', '', '-', '<C-w>-')
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'
hook_add = '''
  let g:user_emmet_leader_key = '<C-y>'
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
  " Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
  vmap <Enter> <Plug>(EasyAlign)
  " Start interactive EasyAlign for a motion/text object (e.g. gaip)
  nmap ga <Plug>(EasyAlign)
'''
