# ---------------------------------------------------------------------------- #
# filer plugins
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
  let g:vaffle_auto_cd = 0
  let g:vaffle_show_hidden_files = 1
  nnoremap <silent> <Space>v :Vaffle<CR>
'''
