# ---------------------------------------------------------------------------- #
# linter plugins
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_error = '>>'
  let g:ale_sign_warning = '> '

  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'

  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

  let g:ale_lint_on_enter = 0

  let g:ale_set_loclist = 0

  let g:ale_set_quickfix = 1
'''

[[plugins]]
repo = 'stubbornella/csslint'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = ['ynkdir/vim-vimlparser']
on_ft = 'vim'
