# ---------------------------------------------------------------------------- #
# searcher plugins
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = '/usr/local/opt/fzf'
