# ---------------------------------------------------------------------------- #
# syntax plugins
# ---------------------------------------------------------------------------- #

[[plugins]]
repo = 'pearofducks/ansible-vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
filetypes = 'scss'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'
on_event = 'BufRead'

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
on_ft = 'php'

[[plugins]]
repo = 'beanworks/vim-phpfmt'
on_ft = 'php'
hook_add = '''
  let g:phpfmt_standard = 'PSR2'
  let g:phpfmt_autosave = 1
'''

[[plugins]]
repo = 'flyinshadow/php_localvarcheck.vim'
on_ft = 'php'
hook_add = '''
  let g:php_localvarcheck_global = 1
'''

[[plugins]]
repo = 'mattn/vim-sqlfmt'
on_ft = 'sql'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'lumiliet/vim-twig'

[[plugins]]
repo = 'mitsuhiko/vim-jinja'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
hook_add = '''
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'Quramy/tsuquyomi'
depends = ['Shougo/vimproc.vim']
on_ft = 'typescript'

[[plugins]]
repo = 'ynkdir/vim-vimlparser'
on_ft = 'vim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'darfink/vim-plist'
on_ft = 'xml'

[[plugins]]
repo = 'avakhov/vim-yaml'
on_ft = 'yaml'
